/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ILadleInterface extends ethers.utils.Interface {
  functions: {
    "build(bytes6,bytes6,uint8)": FunctionFragment;
    "cauldron()": FunctionFragment;
    "close(bytes12,address,int128,int128)": FunctionFragment;
    "destroy(bytes12)": FunctionFragment;
    "joins(bytes6)": FunctionFragment;
    "pour(bytes12,address,int128,int128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "build",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cauldron", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "close",
    values: [BytesLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "destroy", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "joins", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pour",
    values: [BytesLike, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "build", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cauldron", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pour", data: BytesLike): Result;

  events: {};
}

export class ILadle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: ILadleInterface;

  functions: {
    build(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "build(bytes6,bytes6,uint8)"(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cauldron(overrides?: CallOverrides): Promise<[string]>;

    "cauldron()"(overrides?: CallOverrides): Promise<[string]>;

    close(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "close(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    destroy(
      vaultId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "destroy(bytes12)"(
      vaultId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    joins(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "joins(bytes6)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pour(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "pour(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  build(
    seriesId: BytesLike,
    ilkId: BytesLike,
    salt: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "build(bytes6,bytes6,uint8)"(
    seriesId: BytesLike,
    ilkId: BytesLike,
    salt: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cauldron(overrides?: CallOverrides): Promise<string>;

  "cauldron()"(overrides?: CallOverrides): Promise<string>;

  close(
    vaultId: BytesLike,
    to: string,
    ink: BigNumberish,
    art: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "close(bytes12,address,int128,int128)"(
    vaultId: BytesLike,
    to: string,
    ink: BigNumberish,
    art: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  destroy(
    vaultId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "destroy(bytes12)"(
    vaultId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  joins(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "joins(bytes6)"(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  pour(
    vaultId: BytesLike,
    to: string,
    ink: BigNumberish,
    art: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "pour(bytes12,address,int128,int128)"(
    vaultId: BytesLike,
    to: string,
    ink: BigNumberish,
    art: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    build(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        [string, string, string] & {
          owner: string;
          seriesId: string;
          ilkId: string;
        }
      ] & {
        vaultId: string;
        vault: [string, string, string] & {
          owner: string;
          seriesId: string;
          ilkId: string;
        };
      }
    >;

    "build(bytes6,bytes6,uint8)"(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        [string, string, string] & {
          owner: string;
          seriesId: string;
          ilkId: string;
        }
      ] & {
        vaultId: string;
        vault: [string, string, string] & {
          owner: string;
          seriesId: string;
          ilkId: string;
        };
      }
    >;

    cauldron(overrides?: CallOverrides): Promise<string>;

    "cauldron()"(overrides?: CallOverrides): Promise<string>;

    close(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "close(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    destroy(vaultId: BytesLike, overrides?: CallOverrides): Promise<void>;

    "destroy(bytes12)"(
      vaultId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    joins(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "joins(bytes6)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    pour(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "pour(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    build(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "build(bytes6,bytes6,uint8)"(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cauldron(overrides?: CallOverrides): Promise<BigNumber>;

    "cauldron()"(overrides?: CallOverrides): Promise<BigNumber>;

    close(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "close(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    destroy(vaultId: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "destroy(bytes12)"(
      vaultId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    joins(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "joins(bytes6)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pour(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "pour(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    build(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "build(bytes6,bytes6,uint8)"(
      seriesId: BytesLike,
      ilkId: BytesLike,
      salt: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cauldron(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cauldron()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    close(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "close(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    destroy(
      vaultId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "destroy(bytes12)"(
      vaultId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    joins(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "joins(bytes6)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pour(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "pour(bytes12,address,int128,int128)"(
      vaultId: BytesLike,
      to: string,
      ink: BigNumberish,
      art: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
