/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPoolInterface extends ethers.utils.Interface {
  functions: {
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "base()": FunctionFragment;
    "burn(address,address,uint256,uint256)": FunctionFragment;
    "burnForBase(address,uint256,uint256)": FunctionFragment;
    "buyBase(address,uint128,uint128)": FunctionFragment;
    "buyBasePreview(uint128)": FunctionFragment;
    "buyFYToken(address,uint128,uint128)": FunctionFragment;
    "buyFYTokenPreview(uint128)": FunctionFragment;
    "cumulativeBalancesRatio()": FunctionFragment;
    "fyToken()": FunctionFragment;
    "g1()": FunctionFragment;
    "g2()": FunctionFragment;
    "getBaseBalance()": FunctionFragment;
    "getCache()": FunctionFragment;
    "getFYTokenBalance()": FunctionFragment;
    "maturity()": FunctionFragment;
    "mint(address,address,uint256,uint256)": FunctionFragment;
    "mintWithBase(address,address,uint256,uint256,uint256)": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "retrieveBase(address)": FunctionFragment;
    "retrieveFYToken(address)": FunctionFragment;
    "scaleFactor()": FunctionFragment;
    "sellBase(address,uint128)": FunctionFragment;
    "sellBasePreview(uint128)": FunctionFragment;
    "sellFYToken(address,uint128)": FunctionFragment;
    "sellFYTokenPreview(uint128)": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "ts()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "base", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnForBase",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyBase",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyBasePreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyFYToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyFYTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeBalancesRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fyToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "g1", values?: undefined): string;
  encodeFunctionData(functionFragment: "g2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBaseBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getCache", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFYTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maturity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithBase",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [string]): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveBase",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveFYToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "scaleFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellBase",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellBasePreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFYToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFYTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ts", values?: undefined): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "base", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnForBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyBase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyBasePreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyFYToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyFYTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeBalancesRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "g1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "g2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBaseBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCache", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFYTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maturity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintWithBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "retrieveBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveFYToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scaleFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellBase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellBasePreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFYToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFYTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ts", data: BytesLike): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class IPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: IPoolInterface;

  functions: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    base(overrides?: CallOverrides): Promise<[string]>;

    "base()"(overrides?: CallOverrides): Promise<[string]>;

    burn(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burn(address,address,uint256,uint256)"(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    burnForBase(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burnForBase(address,uint256,uint256)"(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyBase(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyBase(address,uint128,uint128)"(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyBasePreview(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "buyBasePreview(uint128)"(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buyFYToken(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyFYToken(address,uint128,uint128)"(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cumulativeBalancesRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    "cumulativeBalancesRatio()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fyToken(overrides?: CallOverrides): Promise<[string]>;

    "fyToken()"(overrides?: CallOverrides): Promise<[string]>;

    g1(overrides?: CallOverrides): Promise<[BigNumber]>;

    "g1()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    g2(overrides?: CallOverrides): Promise<[BigNumber]>;

    "g2()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBaseBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBaseBalance()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCache(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    "getCache()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    getFYTokenBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getFYTokenBalance()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maturity(overrides?: CallOverrides): Promise<[number]>;

    "maturity()"(overrides?: CallOverrides): Promise<[number]>;

    mint(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mint(address,address,uint256,uint256)"(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintWithBase(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintWithBase(address,address,uint256,uint256,uint256)"(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    nonces(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    retrieveBase(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "retrieveBase(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    retrieveFYToken(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "retrieveFYToken(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    scaleFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    "scaleFactor()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    sellBase(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellBase(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellBasePreview(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sellBasePreview(uint128)"(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sellFYToken(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellFYToken(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    ts(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ts()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  base(overrides?: CallOverrides): Promise<string>;

  "base()"(overrides?: CallOverrides): Promise<string>;

  burn(
    baseTo: string,
    fyTokenTo: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burn(address,address,uint256,uint256)"(
    baseTo: string,
    fyTokenTo: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  burnForBase(
    to: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burnForBase(address,uint256,uint256)"(
    to: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyBase(
    to: string,
    baseOut: BigNumberish,
    max: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyBase(address,uint128,uint128)"(
    to: string,
    baseOut: BigNumberish,
    max: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyBasePreview(
    baseOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "buyBasePreview(uint128)"(
    baseOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buyFYToken(
    to: string,
    fyTokenOut: BigNumberish,
    max: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyFYToken(address,uint128,uint128)"(
    to: string,
    fyTokenOut: BigNumberish,
    max: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyFYTokenPreview(
    fyTokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "buyFYTokenPreview(uint128)"(
    fyTokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cumulativeBalancesRatio(overrides?: CallOverrides): Promise<BigNumber>;

  "cumulativeBalancesRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

  fyToken(overrides?: CallOverrides): Promise<string>;

  "fyToken()"(overrides?: CallOverrides): Promise<string>;

  g1(overrides?: CallOverrides): Promise<BigNumber>;

  "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

  g2(overrides?: CallOverrides): Promise<BigNumber>;

  "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBaseBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "getBaseBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCache(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, number]>;

  "getCache()"(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, number]>;

  getFYTokenBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "getFYTokenBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  maturity(overrides?: CallOverrides): Promise<number>;

  "maturity()"(overrides?: CallOverrides): Promise<number>;

  mint(
    to: string,
    remainder: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mint(address,address,uint256,uint256)"(
    to: string,
    remainder: string,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintWithBase(
    to: string,
    remainder: string,
    fyTokenToBuy: BigNumberish,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintWithBase(address,address,uint256,uint256,uint256)"(
    to: string,
    remainder: string,
    fyTokenToBuy: BigNumberish,
    minRatio: BigNumberish,
    maxRatio: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "nonces(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  permit(
    owner: string,
    spender: string,
    amount: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
    owner: string,
    spender: string,
    amount: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  retrieveBase(to: string, overrides?: Overrides): Promise<ContractTransaction>;

  "retrieveBase(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  retrieveFYToken(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "retrieveFYToken(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  scaleFactor(overrides?: CallOverrides): Promise<BigNumber>;

  "scaleFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

  sellBase(
    to: string,
    min: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellBase(address,uint128)"(
    to: string,
    min: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellBasePreview(
    baseIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sellBasePreview(uint128)"(
    baseIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sellFYToken(
    to: string,
    min: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellFYToken(address,uint128)"(
    to: string,
    min: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellFYTokenPreview(
    fyTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sellFYTokenPreview(uint128)"(
    fyTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  ts(overrides?: CallOverrides): Promise<BigNumber>;

  "ts()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    base(overrides?: CallOverrides): Promise<string>;

    "base()"(overrides?: CallOverrides): Promise<string>;

    burn(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    "burn(address,address,uint256,uint256)"(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    burnForBase(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "burnForBase(address,uint256,uint256)"(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    buyBase(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBase(address,uint128,uint128)"(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyBasePreview(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBasePreview(uint128)"(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYToken(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYToken(address,uint128,uint128)"(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cumulativeBalancesRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "cumulativeBalancesRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

    fyToken(overrides?: CallOverrides): Promise<string>;

    "fyToken()"(overrides?: CallOverrides): Promise<string>;

    g1(overrides?: CallOverrides): Promise<BigNumber>;

    "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

    g2(overrides?: CallOverrides): Promise<BigNumber>;

    "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBaseBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getBaseBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCache(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    "getCache()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    getFYTokenBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getFYTokenBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<number>;

    "maturity()"(overrides?: CallOverrides): Promise<number>;

    mint(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    "mint(address,address,uint256,uint256)"(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    mintWithBase(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    "mintWithBase(address,address,uint256,uint256,uint256)"(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    retrieveBase(to: string, overrides?: CallOverrides): Promise<BigNumber>;

    "retrieveBase(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    retrieveFYToken(to: string, overrides?: CallOverrides): Promise<BigNumber>;

    "retrieveFYToken(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    scaleFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "scaleFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

    sellBase(
      to: string,
      min: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBase(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellBasePreview(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBasePreview(uint128)"(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYToken(
      to: string,
      min: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYToken(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ts(overrides?: CallOverrides): Promise<BigNumber>;

    "ts()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    Transfer(
      from: string | null,
      to: string | null,
      value: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;
  };

  estimateGas: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    base(overrides?: CallOverrides): Promise<BigNumber>;

    "base()"(overrides?: CallOverrides): Promise<BigNumber>;

    burn(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burn(address,address,uint256,uint256)"(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    burnForBase(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burnForBase(address,uint256,uint256)"(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyBase(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyBase(address,uint128,uint128)"(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyBasePreview(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBasePreview(uint128)"(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYToken(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyFYToken(address,uint128,uint128)"(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cumulativeBalancesRatio(overrides?: CallOverrides): Promise<BigNumber>;

    "cumulativeBalancesRatio()"(overrides?: CallOverrides): Promise<BigNumber>;

    fyToken(overrides?: CallOverrides): Promise<BigNumber>;

    "fyToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    g1(overrides?: CallOverrides): Promise<BigNumber>;

    "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

    g2(overrides?: CallOverrides): Promise<BigNumber>;

    "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBaseBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getBaseBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCache(overrides?: CallOverrides): Promise<BigNumber>;

    "getCache()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFYTokenBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getFYTokenBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<BigNumber>;

    "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mint(address,address,uint256,uint256)"(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintWithBase(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintWithBase(address,address,uint256,uint256,uint256)"(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    retrieveBase(to: string, overrides?: Overrides): Promise<BigNumber>;

    "retrieveBase(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    retrieveFYToken(to: string, overrides?: Overrides): Promise<BigNumber>;

    "retrieveFYToken(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    scaleFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "scaleFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

    sellBase(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellBase(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellBasePreview(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBasePreview(uint128)"(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYToken(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellFYToken(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    ts(overrides?: CallOverrides): Promise<BigNumber>;

    "ts()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    base(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "base()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burn(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burn(address,address,uint256,uint256)"(
      baseTo: string,
      fyTokenTo: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    burnForBase(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burnForBase(address,uint256,uint256)"(
      to: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyBase(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyBase(address,uint128,uint128)"(
      to: string,
      baseOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyBasePreview(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buyBasePreview(uint128)"(
      baseOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyFYToken(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyFYToken(address,uint128,uint128)"(
      to: string,
      fyTokenOut: BigNumberish,
      max: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cumulativeBalancesRatio(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "cumulativeBalancesRatio()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fyToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fyToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    g1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "g1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    g2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "g2()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBaseBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBaseBalance()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCache(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCache()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFYTokenBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFYTokenBalance()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maturity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maturity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mint(address,address,uint256,uint256)"(
      to: string,
      remainder: string,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintWithBase(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintWithBase(address,address,uint256,uint256,uint256)"(
      to: string,
      remainder: string,
      fyTokenToBuy: BigNumberish,
      minRatio: BigNumberish,
      maxRatio: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    nonces(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    retrieveBase(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "retrieveBase(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    retrieveFYToken(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "retrieveFYToken(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    scaleFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "scaleFactor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellBase(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellBase(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellBasePreview(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sellBasePreview(uint128)"(
      baseIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellFYToken(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellFYToken(address,uint128)"(
      to: string,
      min: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    ts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ts()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
