/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface YieldMathExtensionsInterface extends ethers.utils.Interface {
  functions: {
    "invariant(IPool)": FunctionFragment;
    "maxBaseIn(IPool)": FunctionFragment;
    "maxBaseOut(IPool)": FunctionFragment;
    "maxFYTokenIn(IPool)": FunctionFragment;
    "maxFYTokenOut(IPool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "invariant", values: [string]): string;
  encodeFunctionData(functionFragment: "maxBaseIn", values: [string]): string;
  encodeFunctionData(functionFragment: "maxBaseOut", values: [string]): string;
  encodeFunctionData(
    functionFragment: "maxFYTokenIn",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxFYTokenOut",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "invariant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxBaseIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxBaseOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxFYTokenIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxFYTokenOut",
    data: BytesLike
  ): Result;

  events: {};
}

export class YieldMathExtensions extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: YieldMathExtensionsInterface;

  functions: {
    invariant(pool: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "invariant(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxBaseIn(pool: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxBaseIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxBaseOut(pool: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxBaseOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxFYTokenIn(pool: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxFYTokenIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxFYTokenOut(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxFYTokenOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  invariant(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "invariant(IPool)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxBaseIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "maxBaseIn(IPool)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxBaseOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "maxBaseOut(IPool)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxFYTokenIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "maxFYTokenIn(IPool)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxFYTokenOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

  "maxFYTokenOut(IPool)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    invariant(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "invariant(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxBaseIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxBaseIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxBaseOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxBaseOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFYTokenIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFYTokenIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFYTokenOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFYTokenOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    invariant(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "invariant(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxBaseIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxBaseIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxBaseOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxBaseOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFYTokenIn(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFYTokenIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFYTokenOut(pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFYTokenOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    invariant(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "invariant(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxBaseIn(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxBaseIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxBaseOut(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxBaseOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxFYTokenIn(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxFYTokenIn(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxFYTokenOut(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxFYTokenOut(IPool)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
